### ISSUE TITLE
The provided checkpoint is trained by this code?

### ISSUE THREAD

**Issue by shinshiner** [FoundationVision/OmniTokenizer#13]
Hello, I tried to use the provided checkpoint "imagenet_k600.ckpt" to infer some images and videos, but I found the model cannot read the checkpoint.

After checking, I found there are some typos in the code, namely you use "causal" in model definition, while the corresponding name in checkpoint is "casual", as shown below.

Therefore, I'm not sure whether the open-sourced code is matched with pretrained weights, or is there something I missed?

![image](https://github.com/FoundationVision/OmniTokenizer/assets/24225683/b124b82b-4bc0-4e10-a2f9-333643d28b72)
![image](https://github.com/FoundationVision/OmniTokenizer/assets/24225683/f17b684c-6979-4298-bc1a-a4759ae5dced)

**Comment by wdrink** [comment]
Thanks for pointing this out, there are some typos in the training code so we fix them. Apologize that we overlooked that this would cause problems loading the checkpoint, it has been fixed with the lastest commit.

**Comment by shinshiner** [comment]
The newest commit seems to roll back the typos, it looks like you fix them when open source the code, but it conflicts with the trained checkpoint
