### ISSUE TITLE
Considered doing VQ with LFQ?

### ISSUE THREAD

**Issue by iamlockelightning** [FoundationVision/OmniTokenizer#2]
Thanks for publishing the code! Great work, very inspired!!
As you regard MAGVIT(v1) as a baseline in the experiment, have you considered doing VQ with LFQ (replacing VQGAN), which is used in MAGVIT-v2?

**Comment by wdrink** [comment]
Thank you for your kind words about our work! LFQ, introduced by MAGVITv2, is superior in scaling the codebook size, we will consider incorporating it into the OmniTokenizer.
