### ISSUE TITLE
Similar to issue #2, would you like to compare this ckpt with stability's vqvae/vae and tencent's open-magvit2?

### ISSUE THREAD

**Issue by StarCycle** [FoundationVision/OmniTokenizer#3]
Hi,

Do you compare your ckpt with the vae/vqvae [here](https://github.com/CompVis/latent-diffusion)?

![340554999-596a630a-e4b6-40e6-978f-de8a17c4a241](https://github.com/FoundationVision/OmniTokenizer/assets/33491471/5f71b807-59e4-4b0e-b7a3-f597f487dd60)

If the direct comparison is not reasonable because their ckpts are trained with more data, did they have a version that was only trained with imagenet data but with the same config? Or can you evaluate their ckpt on imagenet even if these are trained on more data...I just want to know which ckpt is most suitable for my current application.

Also tencent released their [Open-MAGVIT2](https://github.com/TencentARC/Open-MAGVIT2)

Best,
StarCycle

**Comment by wdrink** [comment]
Thanks for your great suggestion. We evaluated the reconstruction performance of SD1.4 VAE on ImageNet and the rFID is 0.74. As you say, since they adopt much more training data, it's hard to make a fair comparison with them.
