### ISSUE TITLE
It takes a **HUGE** memory

### ISSUE THREAD

**Issue by lucasjinreal** [FoundationVision/OmniTokenizer#5]
After testing, the OminTokenizer takes an unbelevable memory footprint, my 16GB card OOM directly....

**Comment by wdrink** [comment]
OmniTokenizer is a video model, which always takes more memory than image models. Actually, the parameters of OmniTokenizer is not that much, compared to SD VAE.

**Comment by lucasjinreal** [comment]
If am not read it wrong, it's a image && video tokenizer, this Memory takes 16GB more, is not `not that much`
