### ISSUE TITLE
Could you please adde a script for demo video reconstruction?

### ISSUE THREAD

**Issue by BingliangLi** [FoundationVision/OmniTokenizer#6]
This work looks amazing! I noticed there is a short script for image recon in the readme file, however, could you please also add one for video recon? Also may I ask if I extract each frame from the video and extract image tokens for each frame(with 2D patch emb), will the results be the same as video tokens(with 3D patch emb)?
For example:
```
import something

# read from video.mp4 and pre process

# load and inference model 

# post process and save video to video_recon.mp4
```

**Comment by wdrink** [comment]
Thanks for your question. The script that we provide can do both image and video reconstruction, try to modify the data_dir and data_list to your video datasets.
