### ISSUE TITLE
Question about the gan_feat_loss

### ISSUE THREAD

**Issue by hyc9** [FoundationVision/OmniTokenizer#9]
Thank you for open-sourcing such excellent work! In your code, I noticed that while training the autoencoder, the GAN loss includes both aeloss and gan_feat_loss. To my knowledge, typically only aeloss is used in the training of the generator. Therefore, I wonder whether there's  reference for the gan_feat_loss you used.  I greatly appreciate your help.

**Comment by wdrink** [comment]
Please refer to the TATS paper https://arxiv.org/abs/2204.03638
